-- This file has been generated by Ion. Do not edit.
return {
    [1] = "menu.mainmenu:session/restart",
    [2] = "menu.mainmenu:session/",
    [3] = "run:xlock",
    [4] = "ssh:goatse",
    [5] = "run:firefox",
    [6] = "ssh:brutus",
    [7] = "run:nm-applet",
    [8] = "menu.mainmenu:session/exit",
    [9] = "run:nm-connection-editor",
    [10] = "run:xpdf /home/ronni/Downloads/Opgave\092 i\092 ophavsret\092 til\092 edb-programmer\092 -\092 stillet.pdf",
    [11] = "run:google-chrome",
    [12] = "run:vlc",
}

